services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    depends_on:
      - zookeeper

  rdb:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: rdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - '3307:3306'
    volumes:
      - 'mysqldata:/var/lib/mysql'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'

  flyway:
    image: flyway/flyway
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./infra/rdb/src/main/resources/db/migration:/flyway/sql
      - ./infra/rdb/src/main/resources/db/flyway.conf:/flyway/conf/flyway.config
    depends_on:
      - rdb
    environment:
      FLYWAY_DB_URL: jdbc:mysql://rdb:3306/rdb?useSSL=false&allowPublicKeyRetrieval=true
      FLYWAY_DB_USER: user
      FLYWAY_DB_PASSWORD: password
      FLYWAY_BASELINE_ON_MIGRATE: true

volumes:
  mysqldata:
  redisdata:
