services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2182:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  rdb:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: rdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - '3307:3306'
    volumes:
      - 'mysqldata:/var/lib/mysql'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'

  flyway:
    image: flyway/flyway
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./infra/rdb/src/main/resources/db/migration:/flyway/sql
      - ./infra/rdb/src/main/resources/db/flyway.conf:/flyway/conf/flyway.config
    depends_on:
      - rdb
    environment:
      FLYWAY_DB_URL: jdbc:mysql://rdb:3306/rdb?useSSL=false&allowPublicKeyRetrieval=true
      FLYWAY_DB_USER: user
      FLYWAY_DB_PASSWORD: password
      FLYWAY_BASELINE_ON_MIGRATE: true

volumes:
  mysqldata:
  redisdata:
