datasource:
  mysql:
    writer:
      pool-name: any-community-writer
      driver-class-name: com.mysql.cj.jdbc.Driver
    reader:
      pool-name: any-community-reader
      driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  jpa:
    open-in-view: false
---

spring.config.activate.on-profile: local
datasource:
  mysql:
    writer:
      jdbc-url: jdbc:mysql://127.0.0.1:3307/any-community
      username: user
      password: password
    reader:
      jdbc-url: jdbc:mysql://127.0.0.1:3307/any-community
      username: user
      password: password

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
