server:
  port: 8080

spring:
  profiles:
    include:
      - infra-rdb
      - infra-redis
      - infra-kafka
      - common-util-jwt
    active: local

springdoc:
  swagger-ui:
    path: /swagger-ui
