server:
  port: 8080

spring:
  profiles:
    include:
      - infra-mysql
      - infra-redis
      - infra-kafka
      - util-jwt
    active: local
  threads:
    virtual:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui
