name: Deploy
run-name: Deploy to ${{ inputs.env }} | ${{ inputs.service }} | ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      env:
        description: '배포할 환경을 선택해주세요'
        required: true
        default: 'PROD'
        type: choice
        options:
          - PROD
      service:
        description: '배포할 서비스를 선택해주세요'
        required: true
        default: 'mvc-api'
        type: choice
        options:
          - mvc-api
          - consumer

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: 'gradle'

      - name: Build
        run: |
          ./gradlew app:${{ github.event.inputs.service }}:bootJar --parallel -x test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.PAT }}

      - name: Set Commit Hash as Tag
        id: tag
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use

      - name: Build and Push Docker Image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/any-community/${{ github.event.inputs.service }}:${{ env.tag }} \
            --push ./app/${{ github.event.inputs.service }}
